package com.turt2live.antishare.util;

/**
 * Action enum
 * 
 * @author turt2live
 */
public enum Action{

	GAMEMODE_CHANGE,
	WORLD_CHANGE,
	BLOCK_BREAK,
	BLOCK_PLACE,
	ITEM_THROW,
	ITEM_PICKUP,
	ITEM_THROW_DEATH,
	COMMAND_USED,
	USE_SOMETHING,
	HIT_MOB,
	HIT_PLAYER,
	CRAFTED_ITEM,
	CRAFTED_MOB,
	INTERACT_MOB,
	GAMEMODE_BLOCK_BREAK,
	ENTER_REGION,
	EXIT_REGION,
	PLACE_GAMEMODE_ATTACHMENT,
	REGION_BLOCK_BREAK,
	REGION_BLOCK_PLACE,
	REGION_USE_SOMETHING,
	REGION_INTERACT_MOB,
	REGION_ITEM_THROW,
	REGION_ITEM_PICKUP,
	REGION_HIT_PLAYER,
	REGION_HIT_MOB;

}
