package com.turt2live.antishare.enums;

public enum NotificationType{

	// ILLEGAL actions
	ILLEGAL_BLOCK_PLACE,
	ILLEGAL_BLOCK_BREAK,
	ILLEGAL_CREATIVE_BLOCK_BREAK,
	ILLEGAL_WORLD_CHANGE,
	ILLEGAL_COMMAND,
	ILLEGAL_DEATH,
	ILLEGAL_DROP_ITEM,
	ILLEGAL_INTERACTION,
	ILLEGAL_PLAYER_PVP,
	ILLEGAL_MOB_PVP,
	ILLEGAL_EGG,
	ILLEGAL_BEDROCK,
	ILLEGAL_EXP_BOTTLE,
	ILLEGAL_ITEM_THROW_INTO_REGION,

	// LEGAL actions
	LEGAL_BLOCK_PLACE,
	LEGAL_BLOCK_BREAK,
	LEGAL_CREATIVE_BLOCK_BREAK,
	LEGAL_WORLD_CHANGE,
	LEGAL_COMMAND,
	LEGAL_DEATH,
	LEGAL_DROP_ITEM,
	LEGAL_INTERACTION,
	LEGAL_PLAYER_PVP,
	LEGAL_MOB_PVP,
	LEGAL_EGG,
	LEGAL_BEDROCK,
	LEGAL_EXP_BOTTLE,
	LEGAL_ITEM_THROW_INTO_REGION,

	// GENERAL actions
	GAMEMODE_CHANGE,
	REGION_ENTER,
	REGION_EXIT,
}
